export const projectsDB = [
    {
        name: "Pharmacy Store",
        image: "pharmacy store.png",
        paragraph: "This is a simple e-commerce application built with Node.js and Express.js. Features: User authentication with Passport.js Session management with express-session MongoDB database connection EJS templating and layouts Routes for home, authentication, cart, and admin functionalities",
        github: "https://github.com/Mohamed-Ahmed-Kamel/Pharmacy_Store",
        link: "",
        more: "",
        lang: "HTML - CSS - JS - NodeJS",
        category: ["node"],
    },
    {
        name: "Online Store Back",
        image: "e-commerce.jpg",
        paragraph: "This E-Commerce API is a RESTful API built with Express and MongoDB. It allows users to manage products, blogs, product categories, blog categories, brands, coupons, colors, and enquiries.",
        github: "",
        link: "",
        more: "",
        lang: "NodeJS",
        category: ["node"],
    },
    {
        name: "Online Store Front",
        image: "e-commerce-home.png",
        paragraph: "This E-Commerce App Is The Front-End Of Online Store Back.",
        github: "",
        link: "",
        more: "",
        lang: "React",
        category: ["react"],
    },
    {
        name: "Realtime Pizza Order",
        image: "pizza.png",
        paragraph: "This is a web application built with Express.js, EJS, and MongoDB. Features: User authentication with Passport.js Session management with express-session Flash messages with express-flash Real-time updates with Socket.io",
        github: "https://github.com/Mohamed-Ahmed-Kamel/Realtime_pizza_order",
        link: "",
        more: "",
        lang: "HTML - CSS - JS - NodeJS - Tailwind",
        category: ["tailwind", "node"],
    },
    {
        name: "Product management",
        image: "PMP.png",
        paragraph: "This is a simple product management app that allows you to create, update, delete, and search products. The products are stored in local storage.",
        github: "https://github.com/Mohamed-Ahmed-Kamel/Product-Management-Project",
        link: "https://mohamed-ahmed-kamel.github.io/Product-Management-Project/",
        more: "",
        lang: "HTML - CSS - JS",
        category: ["js"],
    },
    {
        name: "NodeJS Tutorial 1",
        image: "NodeJSTutorial.png",
        paragraph: "This is an Express app that uses EJS as the view engine and MongoDB as the database. The app also includes livereload for auto-refreshing during development. The app can also Create and Delete",
        github: "https://github.com/Mohamed-Ahmed-Kamel/NodeJS-Tutorial-1",
        link: "",
        more: "",
        lang: "HTML - CSS - JS - NodeJS",
        category: ["node"],
    },
    {
        name: "NodeJS Tutorial 2",
        image: "OAuth2.png",
        paragraph: "This is an Express.js application that uses Passport.js for authentication and includes routes for managing a pharmacy, markets, and user authentication.",
        github: "https://github.com/Mohamed-Ahmed-Kamel/NodeJS-Tutorial-2",
        link: "",
        more: "",
        lang: "NodeJS",
        category: ["node"],
    },
    {
        name: "Portfolio Page",
        image: "portfolio.png",
        paragraph: "This is a personal website for a back-end developer named Mohamed. v1",
        github: "https://github.com/Mohamed-Ahmed-Kamel/My-Profile",
        link: "https://mohamed-ahmed-kamel.github.io/My-Profile/",
        more: "",
        lang: "HTML - CSS - JS",
        category: ["html"],
    },
    {
        name: "Weather app project",
        image: "weather app 2.png",
        paragraph: "This is a simple weather app that allows users to search for the weather in a specific city. The app displays the current temperature, humidity, and wind speed for the selected city.",
        github: "https://github.com/Mohamed-Ahmed-Kamel/weather-app",
        link: "",
        more: "",
        lang: "HTML - CSS - JS",
        category: ["js"],
    },
    {
        name: "landing Page Udacity",
        image: "landing page.png",
        paragraph: "This JavaScript code creates a dynamic navigation menu for a webpage with multiple sections. The navigation menu is built by looping over all the sections on the page and creating a list item for each section with a link to that section.",
        github: "https://github.com/Mohamed-Ahmed-Kamel/landing-page-Udacity",
        link: "https://mohamed-ahmed-kamel.github.io/landing-page-Udacity/#section1",
        more: "",
        lang: "HTML - CSS - JS",
        category: ["js"],
    },
];
export const buttons = [
    { name: "html & css", category: 'html' },
    { name: "js", category: 'js' },
    { name: "nodeJS", category: 'node' },
    { name: "reactJS", category: 'react' },
];
